gcp-project-name: ''
bucket_name: raw-data
keggle:
  cricket_match_data: 'utkarshtomar736/ipl-mens-cricket-matches-data-2008-2023'
dataproc:
  region: europe-west1
  cluster_name: dataproc-pyspark-cluster
biglake:
  dataset_name: sports-data
bigquery:
  dataset_name: sports-data
  table_name: your-bigquery-table-name