tables:
  - name: your-project.dataset.table-1
    partition_column: dw_insert_date
    checks:
      - type: null_check
        column: id
      - type: duplicate_check
        column: source_key
      - type: range_check
        column: source_id
        min: 0
        max: 10

  - name: your-project.dataset.table-2
    checks:
      - type: null_check
        column: account__c
      - type: range_check
        column: source_id
        min: 100
        max: 200

